
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class paser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public paser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public paser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public paser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\006\000\002\002\004\000\002\002\003\000\002\003" +
    "\007\000\002\003\007\000\002\004\002\000\002\004\004" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\010\004\ufffd\005\ufffd\006\ufffd\001\002\000" +
    "\010\004\012\005\011\006\010\001\002\000\004\002\007" +
    "\001\002\000\004\002\000\001\002\000\004\002\001\001" +
    "\002\000\006\004\ufffd\005\ufffd\001\002\000\006\004\ufffd" +
    "\006\ufffd\001\002\000\012\002\ufffc\004\ufffc\005\ufffc\006" +
    "\ufffc\001\002\000\006\004\012\006\014\001\002\000\006" +
    "\002\ufffd\004\ufffd\001\002\000\006\002\uffff\004\012\001" +
    "\002\000\006\004\012\005\017\001\002\000\006\002\ufffd" +
    "\004\ufffd\001\002\000\006\002\ufffe\004\012\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\010\002\004\003\005\004\003\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\015\001\001\000\004\004\012\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\004\014" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\017\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$paser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$paser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$paser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public void report_error(String message, Object info) {
        StringBuffer m = new StringBuffer(message);
        if (info instanceof Symbol) {
            if (((Symbol)info).left != 1 && ((Symbol)info).right != 1) {
                if (((Symbol)info).left != -1 && ((Symbol)info).right != -1) {
                    int line = (((Symbol)info).left) + 1;
                    int column = (((Symbol)info).right) + 1;
                    m.append(" (line " + line + " column " + column + ")");
                }
            }
            System.err.println(m);
        }
    }

    public Object stack(int position) {
        return (((Symbol)stack.elementAt(tos + position)).value);
    }

    public void p(String message){
      System.out.println(message);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$paser$actions {
  private final paser parser;

  /** Constructor */
  CUP$paser$actions(paser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$paser$do_action_part00000000(
    int                        CUP$paser$act_num,
    java_cup.runtime.lr_parser CUP$paser$parser,
    java.util.Stack            CUP$paser$stack,
    int                        CUP$paser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$paser$result;

      /* select the action based on the action number */
      switch (CUP$paser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$paser$stack.elementAt(CUP$paser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$paser$stack.elementAt(CUP$paser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$paser$stack.elementAt(CUP$paser$top-1)).value;
		RESULT = start_val;
              CUP$paser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$paser$stack.elementAt(CUP$paser$top-1)), ((java_cup.runtime.Symbol)CUP$paser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$paser$parser.done_parsing();
          return CUP$paser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= header 
            {
              Object RESULT =null;

              CUP$paser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$paser$stack.peek()), ((java_cup.runtime.Symbol)CUP$paser$stack.peek()), RESULT);
            }
          return CUP$paser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // header ::= token1_list TOKEN2 token1_list TOKEN3 token1_list 
            {
              Object RESULT =null;

              CUP$paser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$paser$stack.elementAt(CUP$paser$top-4)), ((java_cup.runtime.Symbol)CUP$paser$stack.peek()), RESULT);
            }
          return CUP$paser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // header ::= token1_list TOKEN3 token1_list TOKEN2 token1_list 
            {
              Object RESULT =null;

              CUP$paser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$paser$stack.elementAt(CUP$paser$top-4)), ((java_cup.runtime.Symbol)CUP$paser$stack.peek()), RESULT);
            }
          return CUP$paser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // token1_list ::= 
            {
              Object RESULT =null;

              CUP$paser$result = parser.getSymbolFactory().newSymbol("token1_list",2, ((java_cup.runtime.Symbol)CUP$paser$stack.peek()), RESULT);
            }
          return CUP$paser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // token1_list ::= token1_list TOKEN1 
            {
              Object RESULT =null;

              CUP$paser$result = parser.getSymbolFactory().newSymbol("token1_list",2, ((java_cup.runtime.Symbol)CUP$paser$stack.elementAt(CUP$paser$top-1)), ((java_cup.runtime.Symbol)CUP$paser$stack.peek()), RESULT);
            }
          return CUP$paser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$paser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$paser$do_action(
    int                        CUP$paser$act_num,
    java_cup.runtime.lr_parser CUP$paser$parser,
    java.util.Stack            CUP$paser$stack,
    int                        CUP$paser$top)
    throws java.lang.Exception
    {
              return CUP$paser$do_action_part00000000(
                               CUP$paser$act_num,
                               CUP$paser$parser,
                               CUP$paser$stack,
                               CUP$paser$top);
    }
}

}
